site_name: Electricidad básica
nav:
  - Inicio: index.md
  - Introducción a la electricidad: 1_introduccion.md
  - El átomo::
    - Estructura del átomo: 2_atomo.md
    - Experimenta: 2_1_experimenta.md
  - La corriente eléctrica: 3_corriente.md
  - El circuito eléctrico::
    - Definición y características: 4_circuito_elec.md
    - Componentes eléctricos: 4_1_componentes_elec.md
  - Símbología eléctrica::
    - Símbolos y esquemas eléctricos: 5_simbolos.md
    - Ejercicios sobre esquemas eléctricos: 5_1_esquemas_ejercicios.md
  - Magnitudes fundamentales eléctricas: 6_magnitudes.md
  - La Ley de Ohm: 7_ley_ohm.md
  - VERSIÓN PDF: pdf/document.pdf


site_url: https://citius70.github.io/electricidad-tecnologia-1eso/
repo_url: https://github.com/citius70/electricidad-tecnologia-1eso.git
repo_name: citius70/electricidad-tecnologia-1eso



theme:
  features:
    - header.autohide
  icon:
    repo: fontawesome/brands/git
  name: material
  language: es
  palette:
    primary: indigo
    accent: indigo
    background: white
    foreground: black
    code: dark
  palette:
    
   # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Cambiar a modo claro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
        
   # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a preferencias de sistema



  features:
    - navigation.top
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch



markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - pymdownx.blocks.caption
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - toc:
      permalink: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  version:
    provider: mike


plugins:
    - with-pdf:
        author: ALBERTO DURÁN PÉREZ
        copyright: ANY TEXT
        #
        cover: true
        back_cover: true
        #cover_title: yyyyy
        cover_subtitle: Tecnología y Digitalización - 1º ESO
        #custom_template_path: TEMPLATES PATH
        #
        toc_title:  Tabla de contenidos
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        two_columns_level: 0
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        #output_path: any-place/document.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true